version: '3'

services:
  app:
    image: vcrostin/shorturl-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - pg
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - network

  pg:
    image: postgres:13
    container_name: postgre
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    networks:
      - network

volumes:
  database:

networks:
  network:
